In [ ]:
# Ruchika Bhat   25070123095
# Aim: Create Dataset and Load Dataset in Pandas Library

In [ ]:
# dataset creation
import pandas as pd

data ={
    "Roll_No.":[101,102,103,104,105],
    "Gender":["Female","Male","Female","Male","Female"],
    "Department":["computer","IT","ENTC","Mechanical","Computer"],
    "CGPA":[8.2,6.4,9.2,9.0,6.7]
}
df = pd.DataFrame(data)
print(df)
# data is transformed in tabular form

# now we will convert this data into csv format
df.to_csv("students.csv",index=False)
print(df.to_csv)
#there won't be indexing in the csv file


# number of rows and columns
print(df.shape)


# number of elements
print(df.size)


# gives full information of the data
df.info()


# does statistical analysis
df.describe()

   Roll_No.  Gender  Department  CGPA
0       101  Female    computer   8.2
1       102    Male          IT   6.4
2       103  Female        ENTC   9.2
3       104    Male  Mechanical   9.0
4       105  Female    Computer   6.7
<bound method NDFrame.to_csv of    Roll_No.  Gender  Department  CGPA
0       101  Female    computer   8.2
1       102    Male          IT   6.4
2       103  Female        ENTC   9.2
3       104    Male  Mechanical   9.0
4       105  Female    Computer   6.7>
(5, 4)
20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No.    5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

         Roll_No.      CGPA
count    5.000000  5.000000
mean   103.000000  7.900000
std      1.581139  1.292285
min    101.000000  6.400000
25%    102.000000  6.700000
50%    103.000000  8.200000
75%    104.000000  9.000000
max    105.000000  9.200000

In [ ]:
# upload the dataset
import pandas as pd
import numpy as np
df1=pd.read_csv('/content/Cars93.csv')
df1

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
# number of rows and columns
print(df1.shape)

(93, 10)

In [ ]:
# does statistical analysis
df1.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
# gives full information of the data
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
# number of elements
print(df1.size)

930

In [ ]:
# display first 5 rows
df1.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
# display last 5 rows
df1.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
# display 5 random rows
df1.sample(5)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
66,Nissan,Maxima,Midsize,21.5,21,Driver only,160,5,28.5,14.0
15,Chevrolet,Lumina_APV,Van,16.3,18,NaN,170,7,30.5,NaN
56,Mazda,RX-7,Sporty,32.5,17,Driver only,255,2,NaN,NaN
46,Hyundai,Sonata,Midsize,13.9,20,NaN,128,5,31.0,14.0
64,Nissan,Altima,Compact,15.7,24,Driver only,150,5,28.5,14.0

In [ ]:
# gives sum of all null values
df1.isnull().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
# tells if there is any duplicate rows
df1.duplicated().sum()

np.int64(0)

In [ ]:
# gives sum of all unique values
df1.nunique()

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64